//
//
//  Ad4MaxBannerViewDelegate.h
//  ad4Max-SampleApp
//
//  Copyright 2011 Publigroupe
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not
//  use this file except in compliance with the License.  You may obtain a copy
//  of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
//  License for the specific language governing permissions and limitations under
//  the License.
//

// ============================================================================


#import "Ad4MaxBannerView.h"

#import <Foundation/Foundation.h>

/**
 Ad4MaxBanner View Delegate protocol
 handle the ad configuration and beaviors
 */
@protocol Ad4MaxBannerViewDelegate <NSObject>

/** @name Mandatory parameters */

/** get the AdBox Identifier 
 @return the adbox identifier as a string
 */
- (NSString*)getAdBoxId;

/** errors handling 
    @param banner the banner which call it delegate
    @param error the error generated by the failed request
 */
- (void)bannerView:(Ad4MaxBannerView *)banner didFailToReceiveAdWithError:(NSError *)error;

@optional
/** @name Optionals parameters */

/** Ad refresh rate
 @return the refresh rate configured
 */
- (NSUInteger)getAdRefreshRate;

/** Ad categories 
 @return the ad categories asked, up to 3 in a single string separeted by commas
 */
- (NSString*)getTargetedPublisherCategories;

/** Ad lang filter 
 @return YES if the lang is forced to the curent device language
 */
- (BOOL)forceLangFilter;

// Detecting When Advertisements Are Loaded
/** banner will load event
    @param banner the loading banner
 */
- (void)bannerViewWillLoadAd:(Ad4MaxBannerView *)banner;

/** banner did load event
 @param banner the loaded banner
 */
- (void)bannerViewDidLoadAd:(Ad4MaxBannerView *)banner;

// Detecting When a User Interacts With an Advertisement
/** user interaction events 
    @param banner the banner concerned by the user interaction
    @param willLeave the action asked by the interaction
    @return YES if the ad is allow to process it action
 */
- (BOOL)bannerViewActionShouldBegin:(Ad4MaxBannerView *)banner willLeaveApplication:(BOOL)willLeave;

@end

/**
 Definition of error codes
 */
enum {
    Ad4MaxUnknownError = 0, /**< Ad4MaxUnknownError */
    Ad4MaxConfigurationError = 1, /**< Ad4MaxConfigurationError */
    Ad4MaxServerFailureError = 2, /**< Ad4MaxServerFailureError */
    Ad4MaxBannerSizeError = 3, /**< Ad4MaxBannerSizeError */
    Ad4MaxBannerVisibilityError = 4, /**< Ad4MaxBannerVisibilityError */
    Ad4MaxNetworkNotReachableError = 5, /**< Ad4MaxNetworkNotReachableError */
    Ad4MaxNoAdsAvailableError = 6 /**< Ad4MaxNoAdsAvailableError */
};
typedef NSUInteger Ad4MaxError;
